// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ssf/sample.proto

/*
	Package ssf is a generated protocol buffer package.

	It is generated from these files:
		ssf/sample.proto

	It has these top-level messages:
		SSFSample
		SSFSpan
*/
package ssf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import encoding_binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SSFSample_Metric int32

const (
	SSFSample_COUNTER   SSFSample_Metric = 0
	SSFSample_GAUGE     SSFSample_Metric = 1
	SSFSample_HISTOGRAM SSFSample_Metric = 2
	SSFSample_SET       SSFSample_Metric = 3
	SSFSample_STATUS    SSFSample_Metric = 4
)

var SSFSample_Metric_name = map[int32]string{
	0: "COUNTER",
	1: "GAUGE",
	2: "HISTOGRAM",
	3: "SET",
	4: "STATUS",
}
var SSFSample_Metric_value = map[string]int32{
	"COUNTER":   0,
	"GAUGE":     1,
	"HISTOGRAM": 2,
	"SET":       3,
	"STATUS":    4,
}

func (x SSFSample_Metric) String() string {
	return proto.EnumName(SSFSample_Metric_name, int32(x))
}
func (SSFSample_Metric) EnumDescriptor() ([]byte, []int) { return fileDescriptorSample, []int{0, 0} }

type SSFSample_Status int32

const (
	SSFSample_OK       SSFSample_Status = 0
	SSFSample_WARNING  SSFSample_Status = 1
	SSFSample_CRITICAL SSFSample_Status = 2
	SSFSample_UNKNOWN  SSFSample_Status = 3
)

var SSFSample_Status_name = map[int32]string{
	0: "OK",
	1: "WARNING",
	2: "CRITICAL",
	3: "UNKNOWN",
}
var SSFSample_Status_value = map[string]int32{
	"OK":       0,
	"WARNING":  1,
	"CRITICAL": 2,
	"UNKNOWN":  3,
}

func (x SSFSample_Status) String() string {
	return proto.EnumName(SSFSample_Status_name, int32(x))
}
func (SSFSample_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorSample, []int{0, 1} }

type SSFSample_Scope int32

const (
	SSFSample_DEFAULT SSFSample_Scope = 0
	SSFSample_LOCAL   SSFSample_Scope = 1
	SSFSample_GLOBAL  SSFSample_Scope = 2
)

var SSFSample_Scope_name = map[int32]string{
	0: "DEFAULT",
	1: "LOCAL",
	2: "GLOBAL",
}
var SSFSample_Scope_value = map[string]int32{
	"DEFAULT": 0,
	"LOCAL":   1,
	"GLOBAL":  2,
}

func (x SSFSample_Scope) String() string {
	return proto.EnumName(SSFSample_Scope_name, int32(x))
}
func (SSFSample_Scope) EnumDescriptor() ([]byte, []int) { return fileDescriptorSample, []int{0, 2} }

// SSFSample is similar of a StatsD-style, point in time metric. It has a Metric
// type, a name, a value and a timestamp. Additionally it can contain a message,
// a status, a sample rate, a map of tags as string keys and values and a unit
// type. Note that SSF doesn't understand units, they are just strings!
type SSFSample struct {
	// The underlying type of the metric
	Metric SSFSample_Metric `protobuf:"varint,1,opt,name=metric,proto3,enum=ssf.SSFSample_Metric" json:"metric,omitempty"`
	// no spaces, but . is allowed
	// e.g.: veneur.bar.baz
	Name       string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value      float32           `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp  int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message    string            `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status     SSFSample_Status  `protobuf:"varint,6,opt,name=status,proto3,enum=ssf.SSFSample_Status" json:"status,omitempty"`
	SampleRate float32           `protobuf:"fixed32,7,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Tags       map[string]string `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Unit       string            `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	// scope indicates to an SSF endpoint what it should do with a metric:
	//
	//     - DEFAULT (or absent) - aggregate counters and gauges locally,
	//       handle histograms and sets globally.
	//     - LOCAL - aggregate all metrics locally.
	//     - GLOBAL - aggregate all metrics globally.
	//
	Scope SSFSample_Scope `protobuf:"varint,10,opt,name=scope,proto3,enum=ssf.SSFSample_Scope" json:"scope,omitempty"`
}

func (m *SSFSample) Reset()                    { *m = SSFSample{} }
func (m *SSFSample) String() string            { return proto.CompactTextString(m) }
func (*SSFSample) ProtoMessage()               {}
func (*SSFSample) Descriptor() ([]byte, []int) { return fileDescriptorSample, []int{0} }

func (m *SSFSample) GetMetric() SSFSample_Metric {
	if m != nil {
		return m.Metric
	}
	return SSFSample_COUNTER
}

func (m *SSFSample) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SSFSample) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SSFSample) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SSFSample) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SSFSample) GetStatus() SSFSample_Status {
	if m != nil {
		return m.Status
	}
	return SSFSample_OK
}

func (m *SSFSample) GetSampleRate() float32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *SSFSample) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SSFSample) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *SSFSample) GetScope() SSFSample_Scope {
	if m != nil {
		return m.Scope
	}
	return SSFSample_DEFAULT
}

// SSFSpan is the primary unit of reporting in SSF. It embeds a set of
// SSFSamples, as well as start/stop time stamps and a parent ID
// (which allows assembling a span lineage for distributed tracing
// purposes).
//
// Note that since this is protobuf, an SSFSpan does not *have* to
// include metrics, just as it does not *have* to include information
// necessary to reconstruct a trace.
//
// Compatibility
//
// On ingestion, an SSFSpan with an empty string for a name field but
// a tag "name" will have that name field replaced with the name tag,
// and the tag is removed.
//
// Metric SSFSamples with a zero sample_rate (indicating it was left
// out) have the sample_rate field set to 1 on ingestion.
//
// Validity Criteria
//
// Programs consuming SSFSpans should take care to only process spans
// and metrics that fulfill the following criteria:
//
// Metrics are considered valid if they have a name and a value.
//
// SSFSpans are considered valid trace spans if they have non-zero id,
// trace_id, start_timestamp and end_timestamp fields.
type SSFSpan struct {
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// the trace_id is the (span) id of the root span
	TraceId int64 `protobuf:"varint,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// the id for this span
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// the (span) id of the direct parent, if this span is not a root
	// span
	ParentId       int64 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	StartTimestamp int64 `protobuf:"varint,5,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64 `protobuf:"varint,6,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	// This flag being true signals that this span was an error. That definition
	// of error is not implicitly fatal, as a span may error but be fixed by
	// a subsequent retry, etc.
	Error bool `protobuf:"varint,7,opt,name=error,proto3" json:"error,omitempty"`
	// The name of the service
	// e.g. "veneur"
	Service string       `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	Metrics []*SSFSample `protobuf:"bytes,10,rep,name=metrics" json:"metrics,omitempty"`
	// Tags are name value pairs that describe a facet of the span. They apply to
	// the *entire* span as opposed to logs which apply to a specific time in
	// the span.
	Tags map[string]string `protobuf:"bytes,11,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// An indicator span is one that represents an action that is included in a
	// service's Service Level Indicators (https://en.wikipedia.org/wiki/Service_level_indicator)
	// This is a signal to receivers that this span may be used to compute SLIs.
	// In practice a service's core feature — the thing you would "bill" for, such
	// as an API call or read/write operation — would be flagged as an indicator
	// span, and its child spans would further describe its duration.
	// It's also worth nothing that an indicator need not be the "root" or first
	// span in a trace. You might have various forms of middleware that happen
	// first or you might have multiple services participating in the same trace.
	Indicator bool `protobuf:"varint,12,opt,name=indicator,proto3" json:"indicator,omitempty"`
	// What to call this span. This could take the form of the endpoint
	// (/customer/:id), the function (class::name.method), a friendly name
	// (foo middleware) or whatever makes sense in your context.
	Name string `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *SSFSpan) Reset()                    { *m = SSFSpan{} }
func (m *SSFSpan) String() string            { return proto.CompactTextString(m) }
func (*SSFSpan) ProtoMessage()               {}
func (*SSFSpan) Descriptor() ([]byte, []int) { return fileDescriptorSample, []int{1} }

func (m *SSFSpan) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SSFSpan) GetTraceId() int64 {
	if m != nil {
		return m.TraceId
	}
	return 0
}

func (m *SSFSpan) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SSFSpan) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *SSFSpan) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *SSFSpan) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *SSFSpan) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *SSFSpan) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SSFSpan) GetMetrics() []*SSFSample {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *SSFSpan) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SSFSpan) GetIndicator() bool {
	if m != nil {
		return m.Indicator
	}
	return false
}

func (m *SSFSpan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SSFSample)(nil), "ssf.SSFSample")
	proto.RegisterType((*SSFSpan)(nil), "ssf.SSFSpan")
	proto.RegisterEnum("ssf.SSFSample_Metric", SSFSample_Metric_name, SSFSample_Metric_value)
	proto.RegisterEnum("ssf.SSFSample_Status", SSFSample_Status_name, SSFSample_Status_value)
	proto.RegisterEnum("ssf.SSFSample_Scope", SSFSample_Scope_name, SSFSample_Scope_value)
}
func (m *SSFSample) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SSFSample) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Metric != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Metric))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSample(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Value != 0 {
		dAtA[i] = 0x1d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Value))))
		i += 4
	}
	if m.Timestamp != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Timestamp))
	}
	if len(m.Message) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintSample(dAtA, i, uint64(len(m.Message)))
		i += copy(dAtA[i:], m.Message)
	}
	if m.Status != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Status))
	}
	if m.SampleRate != 0 {
		dAtA[i] = 0x3d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.SampleRate))))
		i += 4
	}
	if len(m.Tags) > 0 {
		for k, _ := range m.Tags {
			dAtA[i] = 0x42
			i++
			v := m.Tags[k]
			mapSize := 1 + len(k) + sovSample(uint64(len(k))) + 1 + len(v) + sovSample(uint64(len(v)))
			i = encodeVarintSample(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintSample(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintSample(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.Unit) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintSample(dAtA, i, uint64(len(m.Unit)))
		i += copy(dAtA[i:], m.Unit)
	}
	if m.Scope != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Scope))
	}
	return i, nil
}

func (m *SSFSpan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SSFSpan) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Version))
	}
	if m.TraceId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.TraceId))
	}
	if m.Id != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.Id))
	}
	if m.ParentId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.ParentId))
	}
	if m.StartTimestamp != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.StartTimestamp))
	}
	if m.EndTimestamp != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintSample(dAtA, i, uint64(m.EndTimestamp))
	}
	if m.Error {
		dAtA[i] = 0x38
		i++
		if m.Error {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Service) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintSample(dAtA, i, uint64(len(m.Service)))
		i += copy(dAtA[i:], m.Service)
	}
	if len(m.Metrics) > 0 {
		for _, msg := range m.Metrics {
			dAtA[i] = 0x52
			i++
			i = encodeVarintSample(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Tags) > 0 {
		for k, _ := range m.Tags {
			dAtA[i] = 0x5a
			i++
			v := m.Tags[k]
			mapSize := 1 + len(k) + sovSample(uint64(len(k))) + 1 + len(v) + sovSample(uint64(len(v)))
			i = encodeVarintSample(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintSample(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintSample(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if m.Indicator {
		dAtA[i] = 0x60
		i++
		if m.Indicator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintSample(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func encodeVarintSample(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SSFSample) Size() (n int) {
	var l int
	_ = l
	if m.Metric != 0 {
		n += 1 + sovSample(uint64(m.Metric))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSample(uint64(l))
	}
	if m.Value != 0 {
		n += 5
	}
	if m.Timestamp != 0 {
		n += 1 + sovSample(uint64(m.Timestamp))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovSample(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovSample(uint64(m.Status))
	}
	if m.SampleRate != 0 {
		n += 5
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovSample(uint64(len(k))) + 1 + len(v) + sovSample(uint64(len(v)))
			n += mapEntrySize + 1 + sovSample(uint64(mapEntrySize))
		}
	}
	l = len(m.Unit)
	if l > 0 {
		n += 1 + l + sovSample(uint64(l))
	}
	if m.Scope != 0 {
		n += 1 + sovSample(uint64(m.Scope))
	}
	return n
}

func (m *SSFSpan) Size() (n int) {
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovSample(uint64(m.Version))
	}
	if m.TraceId != 0 {
		n += 1 + sovSample(uint64(m.TraceId))
	}
	if m.Id != 0 {
		n += 1 + sovSample(uint64(m.Id))
	}
	if m.ParentId != 0 {
		n += 1 + sovSample(uint64(m.ParentId))
	}
	if m.StartTimestamp != 0 {
		n += 1 + sovSample(uint64(m.StartTimestamp))
	}
	if m.EndTimestamp != 0 {
		n += 1 + sovSample(uint64(m.EndTimestamp))
	}
	if m.Error {
		n += 2
	}
	l = len(m.Service)
	if l > 0 {
		n += 1 + l + sovSample(uint64(l))
	}
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovSample(uint64(l))
		}
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovSample(uint64(len(k))) + 1 + len(v) + sovSample(uint64(len(v)))
			n += mapEntrySize + 1 + sovSample(uint64(mapEntrySize))
		}
	}
	if m.Indicator {
		n += 2
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSample(uint64(l))
	}
	return n
}

func sovSample(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSample(x uint64) (n int) {
	return sovSample(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SSFSample) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSample
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SSFSample: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SSFSample: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metric", wireType)
			}
			m.Metric = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Metric |= (SSFSample_Metric(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Value = float32(math.Float32frombits(v))
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (SSFSample_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleRate", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.SampleRate = float32(math.Float32frombits(v))
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSample
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSample
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSample
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSample
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthSample
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSample(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthSample
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			m.Scope = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Scope |= (SSFSample_Scope(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSample(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSample
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SSFSpan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSample
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SSFSpan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SSFSpan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceId", wireType)
			}
			m.TraceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentId", wireType)
			}
			m.ParentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParentId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimestamp", wireType)
			}
			m.StartTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTimestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimestamp", wireType)
			}
			m.EndTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTimestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Error = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Service = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, &SSFSample{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSample
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSample
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSample
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSample
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthSample
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSample(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthSample
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indicator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Indicator = bool(v != 0)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSample
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSample(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSample
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSample(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSample
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSample
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSample
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSample
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSample
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSample(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSample = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSample   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("ssf/sample.proto", fileDescriptorSample) }

var fileDescriptorSample = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0xad, 0x67, 0x32, 0x93, 0x99, 0x9b, 0x36, 0x9f, 0x65, 0xf5, 0x43, 0x06, 0xaa, 0x10, 0x85,
	0x05, 0x51, 0x81, 0x20, 0x95, 0x05, 0x15, 0xbb, 0xb4, 0x4d, 0x43, 0x68, 0x9a, 0x48, 0x9e, 0x89,
	0xba, 0xac, 0x4c, 0xc6, 0xad, 0x46, 0x34, 0x93, 0x91, 0xed, 0x56, 0xea, 0x5b, 0xf0, 0x28, 0x3c,
	0x02, 0x4b, 0x96, 0x3c, 0x02, 0x2a, 0x2f, 0x82, 0x6c, 0xe7, 0x07, 0x0a, 0x2b, 0x76, 0x3e, 0xf7,
	0x9c, 0xdc, 0xb9, 0xe7, 0xfa, 0x38, 0x80, 0x95, 0xba, 0x78, 0xa5, 0xf8, 0xac, 0xbc, 0x12, 0x9d,
	0x52, 0xce, 0xf5, 0x9c, 0xf8, 0x4a, 0x5d, 0xb4, 0xbe, 0x54, 0x20, 0x4e, 0x92, 0xe3, 0xc4, 0x12,
	0xe4, 0x25, 0x84, 0x33, 0xa1, 0x65, 0x3e, 0xa5, 0xa8, 0x89, 0xda, 0xf5, 0xbd, 0xff, 0x3b, 0x4a,
	0x5d, 0x74, 0x56, 0x7c, 0xe7, 0xd4, 0x92, 0x6c, 0x21, 0x22, 0x04, 0x2a, 0x05, 0x9f, 0x09, 0xea,
	0x35, 0x51, 0x3b, 0x66, 0xf6, 0x4c, 0xb6, 0x21, 0xb8, 0xe1, 0x57, 0xd7, 0x82, 0xfa, 0x4d, 0xd4,
	0xf6, 0x98, 0x03, 0x64, 0x07, 0x62, 0x9d, 0xcf, 0x84, 0xd2, 0x7c, 0x56, 0xd2, 0x4a, 0x13, 0xb5,
	0x7d, 0xb6, 0x2e, 0x10, 0x0a, 0xd5, 0x99, 0x50, 0x8a, 0x5f, 0x0a, 0x1a, 0xd8, 0x56, 0x4b, 0x68,
	0x06, 0x52, 0x9a, 0xeb, 0x6b, 0x45, 0xc3, 0xbf, 0x0e, 0x94, 0x58, 0x92, 0x2d, 0x44, 0xe4, 0x09,
	0xd4, 0x9c, 0xc5, 0x73, 0xc9, 0xb5, 0xa0, 0x55, 0x3b, 0x02, 0xb8, 0x12, 0xe3, 0x5a, 0x90, 0x17,
	0x50, 0xd1, 0xfc, 0x52, 0xd1, 0xa8, 0xe9, 0xb7, 0x6b, 0x7b, 0xf4, 0x5e, 0xb7, 0x94, 0x5f, 0xaa,
	0x5e, 0xa1, 0xe5, 0x2d, 0xb3, 0x2a, 0xe3, 0xef, 0xba, 0xc8, 0x35, 0x8d, 0x9d, 0x3f, 0x73, 0x26,
	0xbb, 0x10, 0xa8, 0xe9, 0xbc, 0x14, 0x14, 0xec, 0x40, 0xdb, 0xf7, 0x07, 0x32, 0x1c, 0x73, 0x92,
	0x47, 0x6f, 0x20, 0x5e, 0xb5, 0x24, 0x18, 0xfc, 0x8f, 0xe2, 0xd6, 0x2e, 0x36, 0x66, 0xe6, 0xb8,
	0x5e, 0x95, 0xdb, 0x9f, 0x03, 0x6f, 0xbd, 0x7d, 0xd4, 0x3a, 0x82, 0xd0, 0xad, 0x9a, 0xd4, 0xa0,
	0x7a, 0x38, 0x9e, 0x8c, 0xd2, 0x1e, 0xc3, 0x1b, 0x24, 0x86, 0xa0, 0xdf, 0x9d, 0xf4, 0x7b, 0x18,
	0x91, 0x2d, 0x88, 0xdf, 0x0d, 0x92, 0x74, 0xdc, 0x67, 0xdd, 0x53, 0xec, 0x91, 0x2a, 0xf8, 0x49,
	0x2f, 0xc5, 0x3e, 0x01, 0x08, 0x93, 0xb4, 0x9b, 0x4e, 0x12, 0x5c, 0x69, 0xed, 0x43, 0xe8, 0xf6,
	0x43, 0x42, 0xf0, 0xc6, 0x27, 0x78, 0xc3, 0x74, 0x3b, 0xeb, 0xb2, 0xd1, 0x60, 0xd4, 0xc7, 0x88,
	0x6c, 0x42, 0x74, 0xc8, 0x06, 0xe9, 0xe0, 0xb0, 0x3b, 0xc4, 0x9e, 0xa1, 0x26, 0xa3, 0x93, 0xd1,
	0xf8, 0x6c, 0x84, 0xfd, 0xd6, 0x73, 0x08, 0xac, 0x11, 0x53, 0x3d, 0xea, 0x1d, 0x77, 0x27, 0xc3,
	0xd4, 0x7d, 0x7e, 0x38, 0x36, 0x6a, 0x64, 0x3e, 0xd3, 0x1f, 0x8e, 0x0f, 0xcc, 0x2f, 0x5b, 0x9f,
	0x7d, 0xa8, 0x9a, 0x05, 0x94, 0xbc, 0x30, 0x37, 0x79, 0x23, 0xa4, 0xca, 0xe7, 0x85, 0x35, 0x1a,
	0xb0, 0x25, 0x24, 0x0f, 0x21, 0xd2, 0x92, 0x4f, 0xc5, 0x79, 0x9e, 0x59, 0xbf, 0x3e, 0xab, 0x5a,
	0x3c, 0xc8, 0x48, 0x1d, 0xbc, 0x3c, 0xb3, 0x79, 0xf1, 0x99, 0x97, 0x67, 0xe4, 0x31, 0xc4, 0x25,
	0x97, 0xa2, 0xd0, 0x46, 0xeb, 0xc2, 0x12, 0xb9, 0xc2, 0x20, 0x23, 0xcf, 0xe0, 0x3f, 0xa5, 0xb9,
	0xd4, 0xe7, 0xeb, 0x3c, 0x05, 0x56, 0x52, 0xb7, 0xe5, 0x74, 0x15, 0xaa, 0xa7, 0xb0, 0x25, 0x8a,
	0xec, 0x17, 0x59, 0x68, 0x65, 0x9b, 0xa2, 0xc8, 0xd6, 0xa2, 0x6d, 0x08, 0x84, 0x94, 0x73, 0x69,
	0xa3, 0x12, 0x31, 0x07, 0x8c, 0x0b, 0x25, 0xe4, 0x4d, 0x3e, 0x15, 0x34, 0x72, 0x79, 0x5c, 0x40,
	0xd2, 0x36, 0x49, 0x35, 0x17, 0xa3, 0x28, 0xd8, 0x08, 0xd5, 0x7f, 0xbf, 0x7f, 0xb6, 0xa4, 0xc9,
	0xee, 0x22, 0x69, 0x35, 0x2b, 0x7b, 0xb0, 0x92, 0x95, 0xbc, 0xf8, 0x23, 0x67, 0x3b, 0x10, 0xe7,
	0x45, 0x96, 0x4f, 0xb9, 0x9e, 0x4b, 0xba, 0x69, 0x27, 0x59, 0x17, 0x56, 0xaf, 0x6c, 0x6b, 0xfd,
	0xca, 0xfe, 0x39, 0x59, 0xef, 0x2b, 0x51, 0x8c, 0xe1, 0x00, 0x7f, 0xbd, 0x6b, 0xa0, 0x6f, 0x77,
	0x0d, 0xf4, 0xfd, 0xae, 0x81, 0x3e, 0xfd, 0x68, 0x6c, 0x7c, 0x08, 0xed, 0x7f, 0xc2, 0xeb, 0x9f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x1c, 0xa6, 0x10, 0x27, 0x04, 0x00, 0x00,
}
